os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10
install: swift package update
script:
  - swift build -c debug
  - swift build -c release
  - swift test #Tests whatever is inside the Test folder
notifications:
  email:
    on_success: never
    on_failure: change
